apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.17.1
  releaseName: cert-manager
  namespace: cert-manager
  valuesInline:
    crds:
      enabled: true
    global:
      leaderElection:
        namespace: cert-manager
