apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  containers:
  - name: test
    image: python:3.14-alpine
    env:
    - name: TZ
      value: Europe/Brussels
    command:
    - sh
    - -c
    - echo 'Welcome Wim' && pip install redis && sleep infinity
    imagePullPolicy: IfNotPresent
