apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-redis
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  encryptedData:
    redis-password: AgAj7ggcp//nvkI3BKr5MyU9/XegirfDms08osFV3mR1T6hyhluDgurYn+J1VJIhamqetTZ2MKYNk4n4U2DhyBEe8fD40AkKuGv8Epviu1X5befSHjxkdYWEZoVL3ewkVfBtOGBPzsqroBe1PZg9NsudgC7Qc8BQB2GmNoxgJ/qY6GKDp4Sv9BhoGtri4+UkBLhOr8hdd7xGvS1CoS2n2bLhxhgpY+slOcPXbaVyEXG7lnYHNShQbrPI1h2UUqVX/r+K3Sh5TGED5ddYPd7PQqx73Gq4k+h+eeNkRV1MSrSPw73CYc28c6jgkDUr4Au+jgklAyFOKzgFxS24RVlNaJCwN9ZZc51xC5LyxPX85/QX5ubsySlFFyuE+I95gEMB48eBZyQpvfDGR1jsUBXILOongXyq/fObaSsBR3t+Cb6IiYIjUKdBpG7IaLFPU5SAiwZ8nC3C0jBhp+qHVbsYTQIaiYmKZ0IH5rtKQJvQErbe/YEfw27EWqJOpd/Bw9mj6489T6fCQUjI8Xy8d7685pjZpGF53QxLCH/D1sJiYGcqiwjg7fwg8xR3Aa/4o/XXiuTk7rjwVC+soZGWKSj4xe0tToIAGOdXygAa21LuMv7lBzmUUDzAevZQRJTGFjoiXHGcuE4jO7FXHBa/yfao6Vvriy5feg1DwxbUwNeEGPioufzfSGEMFtZXllRsLcLGLujwOXIFMFST6Tw=
