apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arc-runners

helmCharts:
- name: gha-runner-scale-set
  repo: oci://ghcr.io/actions/actions-runner-controller-charts
  version: 0.12.1
  releaseName: arc-runner-set1-kubernetes
  namespace: arc-runners
  includeCRDs: true
  valuesFile: values.yaml
