apiVersion: v1
kind: ServiceAccount
metadata:
  name: ui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-ui-user-read-only
rules:
# k8s standard APIs
- apiGroups:
  - ""
  resources:
  - events
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
# Argo APIs. See also https://github.com/argoproj/argo-workflows/blob/main/manifests/cluster-install/workflow-controller-rbac/workflow-aggregate-roles.yaml#L4
- apiGroups:
  - argoproj.io
  resources:
  - eventsources
  - sensors
  - workflows
  - workfloweventbindings
  - workflowtemplates
  - clusterworkflowtemplates
  - cronworkflows
  - workflowtaskresults
  verbs:
  - create
  - delete
  - update
  - patch
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-ui-role
subjects:
- kind: ServiceAccount
  name: ui
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-ui-user-read-only
---
apiVersion: v1
kind: Secret
metadata:
  name: ui-secret
  annotations:
    kubernetes.io/service-account.name: ui
type: kubernetes.io/service-account-token
