apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-region
spec:
  rules:
  - name: check-region
    match:
      any:
      - resources:
          kinds:
          - VPC
    validate:
      failureAction: Audit
      message: "region must be eu-north-1"
      pattern:
        spec:
          forProvider:
            region: "eu-north-1"
