kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: statefulset-sc
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
reclaimPolicy: Delete
---
apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  clusterIP: None
  selector:
    app: simple-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simple-statefulset
spec:
  serviceName: "simple-service"
  replicas: 3
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-container
        image: wimvandenwyngaert/test:2.4.0
        command:
        - /bin/sh
        - -c
        - sleep infinity
        env:
        - name: TZ
          value: "Europe/Brussels"
        volumeMounts:
        - name: data-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: statefulset-sc
      resources:
        requests:
          storage: 1Gi
