apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

helmCharts:
- name: external-secrets
  repo: https://charts.external-secrets.io
  version: 0.19.2
  releaseName: external-secrets
  namespace: external-secrets
