apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kargo

resources:
- namespace.yaml

helmCharts:
- name: kargo
  repo: ghcr.io/akuity/kargo-charts
  version: 1.10.0
  releaseName: kargo
  namespace: kargo
  includeCRDs: true
  valuesFile: values.yaml
