apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnetwork-azure
spec:
  compositeTypeRef:
    apiVersion: platform.wim-vdw.github.io/v1alpha1
    kind: XNetwork
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: TO_PATCH_RG_NAME # will be overwritten via patch
        base:
          apiVersion: azure.upbound.io/v1beta1
          kind: ResourceGroup
          spec:
            providerConfigRef:
              name: default-azure-provider
            forProvider:
              location: TO_PATCH # will be overwritten via patch
              tags:
                environment: development
                managed-by: crossplane
        patches:
        - fromFieldPath: "spec.resourceGroupName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.location"

      - name: TO_PATCH_VNET_NAME # will be overwritten via patch
        base:
          apiVersion: network.azure.upbound.io/v1beta1
          kind: VirtualNetwork
          spec:
            providerConfigRef:
              name: default-azure-provider
            forProvider:
              addressSpace: [] # will be overwritten via patch
              location: TO_PATCH # will be overwritten via patch
              resourceGroupNameSelector:
                matchControllerRef: true
        patches:
        - fromFieldPath: "spec.networkName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.location"
        - fromFieldPath: "spec.networkAddressSpace"
          toFieldPath: "spec.forProvider.addressSpace[0]"
        - fromFieldPath: "spec.resourceGroupName"
          toFieldPath: "spec.forProvider.resourceGroupName"
