apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: rg-test02-ne-crossplane
spec:
  providerConfigRef:
    name: default-azure-provider
  forProvider:
    location: North Europe
    tags:
      environment: development
      managed-by: crossplane
