apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
data:
  index.html: |
    <!doctype html>
    <html lang="">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width"/>
        <title>Cloudflare Tunnel</title>
        <style>
            body {
                min-height: 100vh;
                margin: 0;
                display: flex;
                justify-content: center;
                align-items: center;
                font-family: Tahoma, Verdana, Arial, sans-serif;
                background-color: blue;
                color: white;
            }
            
            h1 {
                text-align: center;
                padding: 1em;
            }
        </style>
    </head>
    <body>
    <h1>Welcome to the Cloudflare Tunnel</h1>
    </body>
    </html>
