apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnel-deployment
  labels:
    app: cloudflare-tunnel
  annotations:
    configmap.reloader.stakater.com/reload: "cloudflare-tunnel-config"
spec:
  selector:
    matchLabels:
      run: cloudflare-tunnel
  replicas: 3
  template:
    metadata:
      labels:
        run: cloudflare-tunnel
    spec:
      volumes:
      - name: app-config
        configMap:
          name: cloudflare-tunnel-config
      containers:
      - name: cloudflare-tunnel-server
        image: nginx:1.31.1-alpine
        env:
        - name: TZ
          value: Europe/Brussels
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: app-config
