# Agent plan to upgrade K3s worker nodes.
# Server nodes should always be upgraded before agent nodes.
# The prepare step will cause upgrade jobs to wait for the server-plan to complete before they execute.
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist
  prepare:
    args:
    - prepare
    - server-plan
    image: rancher/k3s-upgrade
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  version: v1.33.5-rc1+k3s1
