apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: system-upgrade

resources:
- https://github.com/rancher/system-upgrade-controller/releases/download/v0.16.3/crd.yaml
- https://github.com/rancher/system-upgrade-controller/releases/download/v0.16.3/system-upgrade-controller.yaml
