apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyverno

helmCharts:
- name: kyverno
  repo: https://kyverno.github.io/kyverno/
  version: 3.3.4
  releaseName: kyverno
  namespace: kyverno
  includeCRDs: true
