apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keda

helmCharts:
- name: keda
  repo: https://kedacore.github.io/charts
  version: 2.18.0
  releaseName: keda
  namespace: keda
