apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-reader-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader
rules:
- apiGroups: [""]
  resources: ["namespaces", "nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-cluster-resources
subjects:
- kind: ServiceAccount
  name: cluster-reader-sa
  namespace: test01
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-info
spec:
  schedule: "*/5 * * * *" # runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cluster-reader-sa
          restartPolicy: OnFailure
          containers:
          - name: k8s-cluster-info
            image: wimvandenwyngaert/k8s-cluster-info:1.0.5
            args:
            - -show-nodes
            - -show-namespaces
            env:
            - name: TZ
              value: Europe/Brussels
