apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaledobject
spec:
  scaleTargetRef:
    name: blue-dep
  minReplicaCount: 3
  cooldownPeriod: 300
  triggers:
  - type: cron
    metadata:
      timezone: Europe/Brussels
      start: 0 6 * * *
      end: 0 20 * * *
      desiredReplicas: "10"
