apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-reader-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-reader
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-namespaces
subjects:
- kind: ServiceAccount
  name: namespace-reader-sa
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  serviceAccountName: namespace-reader-sa
  restartPolicy: Never
  containers:
  - name: test-container
    image: wimvandenwyngaert/k8s-version-checker:1.0.3
