apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-github-pat-token
spec:
  encryptedData:
    github_token: AgCmqEERhONq0gNXebRMCf+bh8U/OxPrj8CzEUSxRmwR6hMxPfLfr4RrJCpUUH6BJiGmNXXp7Cb6hF+bFv1TnnQAyNMskxLpou3qOgKUrqrabGOyfk9KIjyr8VbZzKH1ypQOfY0PnfRf1E+tAjkvs9fK4rjd+1YQWfCyDeWC9ktvmnRx1XRwquuSG/UXlf7gO0yV9xxoIY24D3yGRzkslk5USe9kyA7t9qG8vPmNXKM6nkYNKQ7zackObeaVAtLmA+cHFCPCn+YkqDUth3x+K4ivI00bnz268h61bvVBn0FzvTUG+EsjDpRnE+Qm3pDefFhhs/FA/BHYtUF/iV08LOiCjkG6tXSYC/pEZzp/u8ufcB3mR+qCeYSkNEfi54ln8RyIxk0I9SvJHfDFB76swzLXHHps6Wh75HRnpA+9WnKNSk+o4csArap35Z2o4lblaGyuFXMI807B4pWsv4s7ROFNQGSqOFWFrQAdYDQt2f93k05ZdrIKiiFcLRhEPeFSvwwV52nhCh6wCoypsJ4AZqRGtBuNsDdxwU8+inIrLvQZoWJ59ZK9z77EFCO3ECuVqn7HqoXtR0xKnMg8rieRqP/neR5ZL4NUX+MMH5Yo1wB50NUmJiyo5OD584AHME3F0zHfyHQM2FTpyfFwVAAqQUom26Ri8RU+3NY4y0cfpm05+Cbj1NUkQc2XF1A48S1CGiKyyZvxN0jnTmSonD8FgOKheY8pYyvIpZTJb0YYBab3oTIDbOUP96Ds
