name: Actions Runner Controller Demo Docker in Docker
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: arc-runner-set2-dockerindocker
    steps:
    - name: Show Docker version
      run: docker version
