name: ARC Demo Docker in Docker
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: arc-runner-set2-dockerindocker
    steps:
    - name: Show Docker version
      run: docker version
    - name: Create a simple Dockerfile
      run: |
        echo "FROM alpine:latest" > Dockerfile
    - name: Display Dockerfile contents
      run: cat Dockerfile
